In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mglearn
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [45]:
sed = pd.read_csv("spambase.csv")
sed = sed.dropna()
names_data = sed.columns[:len(sed.columns) - 1]
name_target = sed.columns[-1]

y = sed[["result"]].to_numpy().ravel()
X = sed.loc[range(0, len(sed)), [name for name in names_data]].to_numpy()
print("X : {}".format(X.shape))
print("y : {}".format(y.shape))



X : (4601, 57)
y : (4601,)


In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

scaler = MinMaxScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train_scaled : {}".format(X_train_scaled))
print("X_test_scaled : {}".format(X_test_scaled))

X_train_scaled : [[0.         0.         0.         ... 0.00170858 0.0020024  0.0030303 ]
 [0.         0.03711485 0.10392157 ... 0.00217885 0.00600721 0.01174242]
 [0.         0.         0.         ... 0.00116387 0.0020024  0.00555556]
 ...
 [0.         0.         0.         ... 0.0011094  0.00070084 0.00119949]
 [0.         0.         0.49019608 ... 0.00168588 0.0010012  0.00246212]
 [0.         0.         0.04705882 ... 0.00067181 0.00470565 0.00883838]]
X_test_scaled : [[3.08370044e-02 9.80392157e-03 5.68627451e-02 ... 1.53064004e-03
  7.20865038e-03 2.31691919e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.86609169e-03
  1.20144173e-03 4.92424242e-03]
 [0.00000000e+00 0.00000000e+00 5.88235294e-01 ... 3.88561053e-04
  2.00240288e-04 1.19949495e-03]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 9.48706310e-04
  5.00600721e-04 2.77777778e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 9.61416251e-04
  2.40288346e-03 3.73737374e-02]
 [5.06607930e-02 0.0000

In [54]:
gnb = GaussianNB()

gnb.fit(X_train_scaled, y_train)

print("Score train : {}".format(gnb.score(X_train_scaled, y_train)))
print("Score test : {}".format(gnb.score(X_test_scaled, y_test)))


Score train : 0.8153623188405797
Score test : 0.8158123370981755
